from random import random, seed

'''
The most general function named random() (not to be confused with the module’s name) produces a float number 
x coming from the range (0.0, 1.0) –in other words: (0.0 <= x < 1.0).
'''
print("random():::")
for i in range(5):
    print(random())

'''
Pseudo-random number generators work by performing some operation on a value. Generally this value is the previous number
generated by the generator. However, the first time you use the generator, there is no previous value.

Seeding a pseudo-random number generator gives it its first "previous" value. Each seed value will 
correspond to a sequence of generated values for a given random number generator. That is, if you provide the 
same seed twice, you get the same sequence of numbers twice.

The seed()function is able to directly set the generator’s seed. We’ll show you two of its variants:

seed() – sets the seed with the current time;
seed(i) – sets the seed with the integer value i.

'''

print()
print("seed():::")

seed(0)
for i in range(5):
    print(random())

seed(0)
for i in range(5):
    print(random())

'''
If you want integer random values, one of the following functions would fit better:

randrange(end)
randrange(beg,end)
randrange(beg, end, step)
randint(left, right)
'''
print()
print("Integer Random Value:::")

from random import randrange, randint

print(randrange(1), end=' ')
print(randrange(0, 1000), end=' ')
print(randrange(0, 1, 1), end=' ')
print(randint(0, 100))

print("10 Random Int::")
for i in range(10):
    print(randint(1, 10), end=',')

'''
It’s a function named in a very suggestive way – choice:

choice(sequence) -> chooses a “random” element from the input sequence and returns it.
sample(sequence, elements_to_chose=1) -> builds a list (a sample) consisting of the elements_to_chose element 
                                         (which defaults to 1) “drawn” from the input sequence.
'''
print()
print("Choice:::")

from random import choice, sample

lst = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

print(choice(lst))
print(sample(lst, 5))
print(sample(lst, 3))
