words = ['cat', 'window', 'defenestrate']

# Measure some strings:
for w in words:
    print(w + ' length is: ', len(w))

# Loop over a slice copy of the entire list.
for w in words[:]:
    if len(w) > 6:
        words.insert(0, 'test')
print(words)

# The range function

for i in range(5):
    print('range 5: ', i)

for i in range(5, 10):
    print('range (5, 5): ', i)

for i in range(0, 9, 3):
    print('range(0, 10, 3): ', i)

# To iterate over the indices of a sequence, you can combine range() and len() as follows:

a = ['Mary', 'had', 'a', 'little', 'lamb']

for i in range(len(a)):
    print(i, a[i])

print(list(range(10)))

# if the set generated by the range() function is empty the loop won't execute its body at all.

for i in range(1, 1):
    print("Value of i is currently ", i)


'''
The set generated by the range() has to be sorted in ascending order. There’s no way to force the range() to create a 
set in a different form. This means that the range()’s second argument must be greater than the first.

Thus, there will be no output here, either →
'''

for i in range(2, 1):
    print("Value of i for range(2, 1) is : ", i)

for i in range(1, 11):
    print(i, "Mississippi")
    i += 2
    print("value of i after increment: ", i)
print("Ready or not, here I come!")